version: 2
updates:
  - package-ecosystem: "npm" # or "yarn" if you use yarn.lock
    directory: "/"           # root directory where package.json is located
    schedule:
      interval: "weekly"     # Check for updates once a week
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "github-actions" # also track GitHub Actions updates
    directory: "/" 
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
